'use client'

// auto-generated by: https://github.com/pmndrs/gltfjsx
// command: npx gltfjsx@6.5.3 palm.gltf --transform --types
// this version has been modified since
import type { Mesh, MeshStandardMaterial, Group } from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// types for the gltf version
type GLTFResult = GLTF & {
    nodes: {
        tronc_tronc1_0: Mesh
        Feuille_1_feuilles_0: Mesh
        Feuille_2_feuilles_0: Mesh
        Feuille_3_feuilles_0: Mesh
        Feuille_4_feuilles_0: Mesh
        Feuille_5_feuilles_0: Mesh
        Feuille_6_feuilles_0: Mesh
        Feuille_7_feuilles_0: Mesh
        Feuille_8_feuilles_0: Mesh
    }
    materials: {
        tronc1: MeshStandardMaterial
        feuilles: MeshStandardMaterial
    }
}

type refType = (ref: Group) => void

export interface IPalmProps extends Partial<Group> {
    ref: refType
}

const PALM_GLTF_PATH = '/assets/3d_models/palm/palm.gltf'

// code for the gltf version
const PalmModel = (props: IPalmProps) => {

    // types problem see: https://github.com/pmndrs/gltfjsx/issues/167
    const { nodes, materials } = useGLTF(PALM_GLTF_PATH) as GLTFResult

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { name, ...palmProps } = props

    return (
        <group name="PalmModel" {...palmProps}>
            <mesh
                castShadow={true} // default is false
                geometry={nodes.tronc_tronc1_0.geometry}
                material={materials.tronc1}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_1_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_2_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_3_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_4_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_5_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_6_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_7_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow={true} // default is false
                geometry={nodes.Feuille_8_feuilles_0.geometry}
                material={materials.feuilles}
            />
        </group>
    )
}

useGLTF.preload(PALM_GLTF_PATH)

export default PalmModel