/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Mesh, MeshStandardMaterial } from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        tronc_tronc1_0: Mesh
        Feuille_1_feuilles_0: Mesh
        Feuille_2_feuilles_0: Mesh
        Feuille_3_feuilles_0: Mesh
        Feuille_4_feuilles_0: Mesh
        Feuille_5_feuilles_0: Mesh
        Feuille_6_feuilles_0: Mesh
        Feuille_7_feuilles_0: Mesh
        Feuille_8_feuilles_0: Mesh
        Feuille_1_feuilles_0001: Mesh
        Feuille_2_feuilles_0001: Mesh
        Feuille_3_feuilles_0001: Mesh
        Feuille_4_feuilles_0001: Mesh
        Feuille_5_feuilles_0001: Mesh
        Feuille_6_feuilles_0001: Mesh
        Feuille_7_feuilles_0001: Mesh
        Feuille_8_feuilles_0001: Mesh
        tronc_tronc1_0001: Mesh
    }
    materials: {
        tronc1: MeshStandardMaterial
        feuilles: MeshStandardMaterial
        ['feuilles.001']: MeshStandardMaterial
        ['tronc1.001']: MeshStandardMaterial
    }
}

export function PalmModel(props) {

    // types problem see: https://github.com/pmndrs/gltfjsx/issues/167
    const { nodes, materials } = useGLTF('/palm8.gltf') as unknown as GLTFResult
    return (
        <group dispose={null}>
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.tronc_tronc1_0.geometry}
                material={materials.tronc1}
                ref={props.ref}
                position={props.position}
                scale={props.scale}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_1_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_2_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_3_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_4_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_5_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_6_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_7_feuilles_0.geometry}
                material={materials.feuilles}
            />
            <mesh
                castShadow
                //receiveShadow
                geometry={nodes.Feuille_8_feuilles_0.geometry}
                material={materials.feuilles}
            />
        </group>
    )
}

useGLTF.preload('/palm8.gltf')